image: jerson/go:1.13

stages:
  - build

server:
  stage: build
  script:
    - make server
  artifacts:
    paths:
      - pgrokd
    expire_in: 1 week

client:
  stage: build
  script:
    - make client
  artifacts:
    paths:
      - pgrok
    expire_in: 1 week
