name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: BinData
      run: |
        cd $GOPATH
        go get -u github.com/jteeuwen/go-bindata/go-bindata
        go install github.com/jteeuwen/go-bindata/go-bindata


    - name: Check out
      uses: actions/checkout@v1

    - name: Setup Modules
      run: |
        echo "set modules"
        export GO111MODULE=on
        export GOPROXY=https://goproxy.io
        export PATH="$GOPATH/bin:$PATH"
        export PATH="$GOROOT/bin:$PATH"
        echo $PATH
        echo "ls gopath"
        ls "$GOPATH/bin"
        echo "ls goroot"
        ls "$GOROOT/bin"
        which go-bindata || echo "error"
        go env

    - name: Deps
      run: make deps

    - name: Build Client
      run: make client

    - name: Build Server
      run: make server